### PR TITLE
wait for module startup at reset

### PR DESCRIPTION
**Pull request by gtortone**
Hi,
I fixed a bug in AT+RST and added a small delay after module reset due to some ESP32 modules that need time to startup...

### CODE REVIEW

**Comment by JAndrassy** [comment]
did you experience some problems? because readRX is patient after reset. it skips 70 lines (presumably of startup log) before giving up

**Comment by JAndrassy** [comment]
why did you replace readRX with sendCommand? readRX("ready") waits for "ready". sendCommand("ready") sends ready and doesn"t wait.
firmware sends ready when it is booted

**Comment by gtortone** [comment]
Hi,
your repo has sendCommand while my commit includes readRx...

**Comment by JAndrassy** [comment]
sorry, it was late and I thought I see the problem.
but  `readRX` instead of `sendCommand` doesn't commit the AT+RST with /r/n

**Comment by JAndrassy** [comment]
I think this solves the reset https://github.com/JAndrassy/WiFiEspAT/commit/5f016cee6833ba9a753284ce78f96a43db53334d

**Pull request closed without merging**
